build:
  environment:
    python: 3.10.10
  nodes:
    my-tests:
      dependencies:
        before:
          - "pip install --upgrade 'tox>=4,<5'"
          - "pip install --upgrade 'poetry>=1.4,<2.0'"
    analysis:
      tests:
        override:
          - py-scrutinizer-run
checks:
  python:
    code_rating: true
    duplicate_code: true
