name: "Enhancement"
title: "🔧 Enhancement"
description: "Enhancement"
labels: ["kind: enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: What needs work?
      placeholder: Describe the feature that could be improved.
    validations:
      required: true
