name: labels
on:
  push:
    branches: [main, master]
jobs:
  labels:
    name: sync issue labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure issue labels
        uses: lannonbr/issue-label-manager-action@3.0.1
        with:
          delete: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
