# SPDX-License-Identifier Apache-2.0
# Source: https://github.com/dmyersturnbull/tyranno
name: on-push-deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ./.github/workflows/test-matrix.yaml
      - name: Publish
        uses: ./.github/workflows/deploy.yaml
      - name: Notify
        uses: ./.github/workflows/notify.yaml
        with:
          job_status: ${{ job.status }}
        if: ${{ always() }}
