# SPDX-License-Identifier Apache-2.0
# Source: https://github.com/dmyersturnbull/tyranno
name: on-pull-test

on:
  pull_request:
    types: [ready_for_review]
    branches: [main]
    paths-ignore: ["**/*.md", "**/*.rst"]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test-matrix.yaml
