# SPDX-License-Identifier Apache-2.0
# Source: https://github.com/dmyersturnbull/tyranno

name: check

on:
  schedule:
    - cron: 0 7 * * 6

jobs:
  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
      - name: Autobuild with CodeQL
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
