name: slack-notify

on:
  workflow_call:
    inputs:
      status:
        type: string
        description: Job status
        required: true
    secrets:
      SLACK_WEBHOOK:
        description: Slack webhook
        required: false

jobs:
  notify-on-slack:
    name: Notify on Slack
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job_status }}
          SLACK_LINK_NAMES: true
          MSG_MINIMAL: true
        if: ${{ SLACK_WEBHOOK }} != ''
