# Reusable test
name: test
on:
  workflow_call:
jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        # :tyranno: python-version: ${.deps.python~.semver_minor(@)~}
        python-version: ["3.11"]
    name: "test on ${{ matrix.os }}/py${{ matrix.python-version }}"
    uses: ./.github/workflows/test-one.yaml
